<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#TODO" data-toc-modified-id="TODO-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>TODO</a></span></li></ul></div>

In [2]:
import os
import pandas as pd
import numpy as np

from ipyfilechooser import FileChooser
from IPython.display import display

In [3]:
def display_file(search_request="item you are looking for"):
    folder_chooser = FileChooser(title=f'<b>Select the {search_request}</b>')
    display(folder_chooser)
    return folder_chooser

In [4]:
search_request = "folder containing annotation files"
folder_chooser = display_file(search_request)

FileChooser(path='/Users/kalindi/Desktop/dt/spyfish/spyfish_analysis/notebooks_metadata_and_annotations', file…

In [6]:
selected_folder = folder_chooser.selected_path
assert selected_folder != None, "Select folder in the cell above."
print(f"The selected folder is {selected_folder}")
all_files = os.listdir(selected_folder)
# TODO should only be CSV files
all_tab_files = [os.path.join(selected_folder, file) for file in all_files if file.endswith(".xlsx") or file.endswith(".xls") or file.endswith(".csv")]
all_tab_files

The selected folder is /Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export


['/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_MPAMAR dataTe Whanganui-O-Hei BUV 2022.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_MPAMAR data Akaroa Pohatu BUV 2021 - Video analysis data sheet - DOC-7166069.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_MPAMAR Data BUV Tonga Island 2021 Video analysis data sheet.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_Te Whanganui-O-Hei BUV 2016 DATA - DOC-7180687.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_Te Whanganui-O-Hei BUV 2020 DATA - DOC-7180706.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/annotations_buv_doc_MPAMAR Data BUV Horoirangi 2021 - Video analysis sheet.xlsx',
 '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/an

In [8]:
dfs = []
# check lines
count_lines = 0
for f in all_tab_files:
    # TODO remove the xlsx option, make output CSV
    if f.endswith(".xlsx"):
        data = pd.read_excel(f, 'Sheet1')
    elif f.endswith(".csv"):
        data = pd.read_csv(f)
    else:
        print(f"{f} not exported")
        continue
    count_lines += data.shape[0]
    dfs.append(data)

    

combined_df = pd.concat(dfs, axis=0, ignore_index=True)
assert combined_df.shape[0] == count_lines

# make export folder in folder containing the annotation files 
path_to_export = os.path.join(selected_folder, "export")
os.makedirs(path_to_export, exist_ok=True)
export_excel_file_name = f"annotations_buv_doc_current.csv"
export_location = os.path.join(path_to_export, export_excel_file_name)
print(f"File containing the conacatenated annotations exported to: '{export_location}'")
combined_df.to_csv(export_location)  

File containing the conacatenated annotations exported to: '/Users/kalindi/Desktop/dt/spyfish/Spyfish - 3.12/Video analysis/export/export/annotations_buv_doc_current.csv'


In [9]:
combined_df.sample(20)

Unnamed: 0           DeploymentID        ScientificName TimeOfMax  \
4736          479  HOR_20211122_BUV_0012  Chelidonichthys kumu  00:06:11   
7952         2081  AKA_20170223_BUV_0026    Pseudolabrus miles  00:12:00   
6190          306  AKA_20170223_BUV_0009     Parapercis colias  00:19:26   
7508         1636  AKA_20170223_BUV_0022  Notolabrus celidotus  00:19:51   
7544         1672  AKA_20170223_BUV_0022     Parapercis colias  00:30:08   
12429        6563  AKA_20170223_BUV_0061    Pseudolabrus miles  00:14:23   
1629         1571  AKA_20210127_BUV_0023   Notolabrus fucicola  00:10:27   
13141        7276  AKA_20170223_BUV_0069     Parapercis colias  00:31:43   
7830         1959  AKA_20170223_BUV_0025    Pseudolabrus miles  00:33:21   
5742         1487  HOR_20211122_BUV_0032     Parapercis colias  00:23:00   
672           614  AKA_20210127_BUV_0009     Meuschenia scaber  00:26:43   
13986        8121  AKA_20170223_BUV_0079   Notolabrus fucicola  00:31:36   
2462         2404  AKA_20210127_BUV_0034    Pseudolabrus miles  00:27:26   
943           885  AKA_20210127_BUV_0013     Parapercis colias  00:20:37   
1360         1302  AKA_20210127_BUV_0018    Pseudolabrus miles  00:16:51   
8717         2846  AKA_20170223_BUV_0031       Jasus edwardsii  00:11:57   
13055        7190  AKA_20170223_BUV_0069    Pseudolabrus miles  00:31:47   
6236          355  AKA_20170223_BUV_0011  Notolabrus celidotus  00:21:26   
12055        6189  AKA_20170223_BUV_0058     Parapercis colias  00:16:18   
7169         1297  AKA_20170223_BUV_0020     Parapercis colias  00:11:03   

      MaxInterval AnnotatedBy  IntervalAnnotation  ConfidenceAgreement  
4736          1.0      expert                  30                  NaN  
7952          1.0      expert                  30                  NaN  
6190          3.0      expert                  30                  NaN  
7508          1.0      expert                  30                  NaN  
7544          3.0      expert                  30                  NaN  
12429         2.0      expert                  30                  NaN  
1629          1.0      expert                  30                  NaN  
13141         6.0      expert                  30                  NaN  
7830          1.0      expert                  30                  NaN  
5742          4.0      expert                  30                  NaN  
672           1.0      expert                  30                  NaN  
13986         1.0      expert                  30                  NaN  
2462          3.0      expert                  30                  NaN  
943           7.0      expert                  30                  NaN  
1360          3.0      expert                  30                  NaN  
8717          1.0      expert                  30                  NaN  
13055         2.0      expert                  30                  NaN  
6236          1.0      expert                  30                  NaN  
12055        18.0      expert                  30                  NaN  
7169          2.0      expert                  30                  NaN

In [17]:
# check again with species name checker to make sure all is good
species_names = combined_df["ScientificName"].unique()
for i in np.sort(species_names[1:]):
#     print(i, end=', ')
    print(i)
        

Aplodactylus arctidens
Arripis trutta
Bathytoshia brevicaudata
Bodianus unimaculatus
Cephaloscyllium isabella
Chelidonichthys kumu
Chirodactylus spectabilis
Chironemus marmoratus
Chromis dispila
Conger verreauxi
Congiopodus leucopaecilus
Dipturus innominatus
Dipturus nasutus
Eptatretus cirrhatus
FIXChondrichthyes
FIXUnidentified
FIXUnidentified epipelagic
Galeorhinus galeus
Gymnothorax prasinus
Helicolenus percoides
Hemerocoetes monopterygius
Hypoplectrodes huntii
Jasus edwardsii
Latridopsis ciliaris
Latris lineata
Lotella rhacina
Macroctopus maorum
Meuschenia scaber
Mustelus lenticulatus
NULL SAMPLE
Nemadactylus douglasii
Nemadactylus macropterus
Notolabrus celidotus
Notolabrus cinctus
Notolabrus fucicola
Notorynchus cepedianus
Odax pullus
Pagrus auratus
Parapercis colias
Pseduolabrus miles
Pseudocaranx georgianus
Pseudolabrus miles
Pseudophycis bachus
Pseudophycis barbata
Scorpis lineolata
Scorpis violacea
Seriola lalandi
Squalus acanthias
Thyrsites atun
Trachurus novaezelandiae
Upen

In [18]:
combined_df["MaxInterval"].unique()

array([nan, 1.0, 4.0, 2.0, 3.0, 5.0, 6.0, 7.0, 9.0, 8.0, 11.0, 10.0, 17.0,
       15.0, 12.0, 14.0, 16.0, 13.0, 23.0, 22.0, 24.0, 25.0, 19.0, 20.0,
       18.0, 21, 'NULL SAMPLE', 0.0], dtype=object)

In [24]:
combined_df["TimeOfMax"].unique()

array([nan, '00:27:56', '00:19:44', ..., '00:34:07', '00:00:05',
       '00:00:23'], dtype=object)

In [13]:
surveyIDs = combined_df['DeploymentID'].dropna().str[:16].unique()
surveyIDs, len(surveyIDs)

(array(['AHE_20220422_BUV', 'AKA_20210127_BUV', 'TON_20211026_BUV',
        'AHE_20160819_BUV', 'AHE_20200301_BUV', 'HOR_20211122_BUV',
        'AHE_20180301_BUV', 'AKA_20170223_BUV'], dtype=object),
 8)

In [14]:
survey_text = """PAR_20120224_BUV
SLI_20110413_BUV
TON_20221205_BUV
RON_20210125_BUV
ANG_20210313_BUV
AHE_20220422_BUV
TON_20211026_BUV
HOR_20211122_BUV
KOK_20240219_BUV
SLI_20240124_BUV
TUH_20210309_BUV
CRP_20220407_BUV
SLI_20220228_BUV
TAW_20220407_BUV
KAP_20200726_BUV
TUH_20200830_BUV
AKA_20170223_BUV
OKU_20230327_BUV
OKU_20201001_BUV
AHE_20230515_BUV
WGI_20220518_BUV
AKA_20181216_BUV
HOR_20240408_BUV
TUH_20240307_BUV
AHE_20200301_BUV
AHE_20180301_BUV
AHE_20160819_BUV
POU_20170223_BUV
POU_20181216_BUV
AKA_20230201_BUV
POU_20230201_BUV
AKA_20210127_BUV
POU_20210127_BUV
AHE_20220422_BUV
AHE_20240501_BUV"""
surveys = survey_text.split("\n")
print(surveys)

['PAR_20120224_BUV', 'SLI_20110413_BUV', 'TON_20221205_BUV', 'RON_20210125_BUV', 'ANG_20210313_BUV', 'AHE_20220422_BUV', 'TON_20211026_BUV', 'HOR_20211122_BUV', 'KOK_20240219_BUV', 'SLI_20240124_BUV', 'TUH_20210309_BUV', 'CRP_20220407_BUV', 'SLI_20220228_BUV', 'TAW_20220407_BUV', 'KAP_20200726_BUV', 'TUH_20200830_BUV', 'AKA_20170223_BUV', 'OKU_20230327_BUV', 'OKU_20201001_BUV', 'AHE_20230515_BUV', 'WGI_20220518_BUV', 'AKA_20181216_BUV', 'HOR_20240408_BUV', 'TUH_20240307_BUV', 'AHE_20200301_BUV', 'AHE_20180301_BUV', 'AHE_20160819_BUV', 'POU_20170223_BUV', 'POU_20181216_BUV', 'AKA_20230201_BUV', 'POU_20230201_BUV', 'AKA_20210127_BUV', 'POU_20210127_BUV', 'AHE_20220422_BUV', 'AHE_20240501_BUV']


In [15]:
common = set(surveyIDs) & set(surveys)
only_in_annotations = set(surveyIDs) - set(surveys)
only_in_surveys = set(surveys) - set(surveyIDs)
common_list = sorted(list(common))
only_in_annotations_list = sorted(list(only_in_annotations))
only_in_surveys_list = sorted(list(only_in_surveys))

print(f"Reviewing files annotations and surveys, there are {len(common)} SurveyIDs in common." )
print(f"The two files have the following {len(common)} SurveyIds in common:")
print(common_list)
print(f"The {len(only_in_annotations)} SurveyIDs present only in annotations are:")
print(only_in_annotations_list)
print(f"The {len(only_in_surveys)} SurveyIDs present only in surveys are:")
print(only_in_surveys_list)

Reviewing files annotations and surveys, there are 8 SurveyIDs in common.
The two files have the following 8 SurveyIds in common:
['AHE_20160819_BUV', 'AHE_20180301_BUV', 'AHE_20200301_BUV', 'AHE_20220422_BUV', 'AKA_20170223_BUV', 'AKA_20210127_BUV', 'HOR_20211122_BUV', 'TON_20211026_BUV']
The 0 SurveyIDs present only in annotations are:
[]
The 26 SurveyIDs present only in surveys are:
['AHE_20230515_BUV', 'AHE_20240501_BUV', 'AKA_20181216_BUV', 'AKA_20230201_BUV', 'ANG_20210313_BUV', 'CRP_20220407_BUV', 'HOR_20240408_BUV', 'KAP_20200726_BUV', 'KOK_20240219_BUV', 'OKU_20201001_BUV', 'OKU_20230327_BUV', 'PAR_20120224_BUV', 'POU_20170223_BUV', 'POU_20181216_BUV', 'POU_20210127_BUV', 'POU_20230201_BUV', 'RON_20210125_BUV', 'SLI_20110413_BUV', 'SLI_20220228_BUV', 'SLI_20240124_BUV', 'TAW_20220407_BUV', 'TON_20221205_BUV', 'TUH_20200830_BUV', 'TUH_20210309_BUV', 'TUH_20240307_BUV', 'WGI_20220518_BUV']


In [16]:

# Find presence of specific SurveyIDs
df2 = combined_df[combined_df['DeploymentID'].str[:16].isin(['TON_20221205_BUV'])]
df2


Empty DataFrame
Columns: [Unnamed: 0, DeploymentID, ScientificName, TimeOfMax, MaxInterval, AnnotatedBy, IntervalAnnotation, ConfidenceAgreement]
Index: []

In [14]:
df2.drop_duplicates()

Empty DataFrame
Columns: [Unnamed: 0, FileName, DeploymentID, ScientificName, TimeOfMax, MaxInterval, 0, 1, annotatedBy, interval_annotation, confidence_agreement]
Index: []

array([nan, 21, 3, 14, 1, 2, 13, 6, 7, '>20', 27, 45, 25, 11, 30, '>30',
       5, 26, 20, 8, 17, 16, 12, 15, 10, 32, 9, 35, 24, 34, 22, 28, 40, 4,
       29, ' ', '  ', 23, 19, 18, 'BAD DEPLOYMENT', 'NULL SAMPLE'],
      dtype=object)